// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  accessCode: __t.string().name("access_code"),
  creatorNickname: __t.string().name("creator_nickname"),
  mimeType: __t.string().name("mime_type"),
  photoBlob: __t.byteArray().name("photo_blob"),
  plantAnswerType: __t.string().name("plant_answer_type"),
  plantCorrectName: __t.string().name("plant_correct_name"),
  plantCorrectType: __t.string().name("plant_correct_type"),
  timestamp: __t.f64(),
});
