// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.identity().name("user_id"),
  experiencePoints: __t.f64().name("experience_points"),
  seeds: __t.f64(),
  petType: __t.string().name("pet_type"),
  petStage: __t.f64().name("pet_stage"),
  petName: __t.string().name("pet_name"),
  hasHat: __t.bool().name("has_hat"),
  hatEquipped: __t.bool().name("hat_equipped"),
  xpBoostCount: __t.f64().name("xp_boost_count"),
});
