// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminActivateKey = __t.object("AdminActivateKey", {
  key: __t.string(),
  active: __t.bool(),
});
export type AdminActivateKey = __Infer<typeof AdminActivateKey>;

export const AiProxyUrl = __t.object("AiProxyUrl", {
  url: __t.string(),
});
export type AiProxyUrl = __Infer<typeof AiProxyUrl>;

export const Claim = __t.object("Claim", {
  id: __t.u64(),
  missionId: __t.string(),
  claimDate: __t.string(),
});
export type Claim = __Infer<typeof Claim>;

export const ClassSessions = __t.object("ClassSessions", {
  accessCode: __t.string(),
  creatorId: __t.identity(),
  startTime: __t.f64(),
  endTime: __t.f64(),
});
export type ClassSessions = __Infer<typeof ClassSessions>;

export const ClassSessionsUploads = __t.object("ClassSessionsUploads", {
  accessCode: __t.string(),
  creatorNickname: __t.string(),
  mimeType: __t.string(),
  photoBlob: __t.string(),
  plantAnswerType: __t.string(),
  reason: __t.string(),
  plantCorrectName: __t.string(),
  plantCorrectScientificName: __t.string(),
  plantCorrectType: __t.string(),
  plantCorrectFunFact: __t.string(),
  timestamp: __t.f64(),
});
export type ClassSessionsUploads = __Infer<typeof ClassSessionsUploads>;

export const Data = __t.object("Data", {
  isPlant: __t.bool(),
  plantCorrectName: __t.string(),
  plantCorrectScientificName: __t.string(),
  plantCorrectType: __t.string(),
  plantCorrectFunFact: __t.string(),
});
export type Data = __Infer<typeof Data>;

export const GetMyMissionClaims = __t.object("GetMyMissionClaims", {});
export type GetMyMissionClaims = __Infer<typeof GetMyMissionClaims>;

export const GetUserProfile = __t.object("GetUserProfile", {});
export type GetUserProfile = __Infer<typeof GetUserProfile>;

export const PlantDetail = __t.object("PlantDetail", {
  flowerLanguage: __t.string(),
  bloomingSeason: __t.string(),
  description: __t.string(),
});
export type PlantDetail = __Infer<typeof PlantDetail>;

export const PlantTypes = __t.object("PlantTypes", {
  name: __t.string(),
  description: __t.string(),
  hints: __t.string(),
  extras: __t.string(),
  icons: __t.string(),
});
export type PlantTypes = __Infer<typeof PlantTypes>;

export const User = __t.object("User", {
  id: __t.identity(),
  name: __t.string(),
  role: __t.string(),
});
export type User = __Infer<typeof User>;

export const UserDailyMissionClaims = __t.object("UserDailyMissionClaims", {
  id: __t.u64(),
  userId: __t.identity(),
  missionId: __t.string(),
  claimDate: __t.string(),
});
export type UserDailyMissionClaims = __Infer<typeof UserDailyMissionClaims>;

export const UserProfile = __t.object("UserProfile", {
  userId: __t.identity(),
  experiencePoints: __t.f64(),
  seeds: __t.f64(),
  petType: __t.string(),
  petStage: __t.f64(),
  petName: __t.string(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const UserUploads = __t.object("UserUploads", {
  userId: __t.identity(),
  mimeType: __t.string(),
  photoBlob: __t.string(),
  plantAnswerType: __t.string(),
  reason: __t.string(),
  plantCorrectName: __t.string(),
  plantCorrectScientificName: __t.string(),
  plantCorrectType: __t.string(),
  plantCorrectFunFact: __t.string(),
  timestamp: __t.f64(),
});
export type UserUploads = __Infer<typeof UserUploads>;

