// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminActivateKey = __t.object("AdminActivateKey", {
  key: __t.string(),
  active: __t.bool(),
});
export type AdminActivateKey = __Infer<typeof AdminActivateKey>;

export const ClassSessions = __t.object("ClassSessions", {
  accessCode: __t.string(),
  creatorId: __t.identity(),
  startTime: __t.f64(),
  endTime: __t.f64(),
});
export type ClassSessions = __Infer<typeof ClassSessions>;

export const ClassSessionsUploads = __t.object("ClassSessionsUploads", {
  accessCode: __t.string(),
  creatorNickname: __t.string(),
  mimeType: __t.string(),
  photoBlob: __t.byteArray(),
  plantAnswerType: __t.string(),
  plantCorrectName: __t.string(),
  plantCorrectType: __t.string(),
  timestamp: __t.f64(),
});
export type ClassSessionsUploads = __Infer<typeof ClassSessionsUploads>;

export const GetUserProfile = __t.object("GetUserProfile", {});
export type GetUserProfile = __Infer<typeof GetUserProfile>;

export const PlantTypes = __t.object("PlantTypes", {
  name: __t.string(),
  description: __t.string(),
  hints: __t.string(),
  extras: __t.string(),
  icons: __t.string(),
});
export type PlantTypes = __Infer<typeof PlantTypes>;

export const UploadRecords = __t.object("UploadRecords", {
  userId: __t.identity(),
  mimeType: __t.string(),
  photoBlob: __t.byteArray(),
  plantName: __t.string(),
  plantType: __t.string(),
  timestamp: __t.f64(),
});
export type UploadRecords = __Infer<typeof UploadRecords>;

export const User = __t.object("User", {
  id: __t.identity(),
  name: __t.string(),
  role: __t.string(),
});
export type User = __Infer<typeof User>;

export const UserProfile = __t.object("UserProfile", {
  userId: __t.identity(),
  experiencePoints: __t.f64(),
  seeds: __t.f64(),
  petType: __t.string(),
  petStage: __t.f64(),
  petName: __t.string(),
});
export type UserProfile = __Infer<typeof UserProfile>;

