// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.identity().name("user_id"),
  mimeType: __t.string().name("mime_type"),
  photoBlob: __t.byteArray().name("photo_blob"),
  plantName: __t.string().name("plant_name"),
  plantType: __t.string().name("plant_type"),
  timestamp: __t.f64(),
});
