// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActivateAdminReducer from "../activate_admin_reducer";
import CreateClassSessionReducer from "../create_class_session_reducer";
import CreateNewUserReducer from "../create_new_user_reducer";
import UploadPlantPhotoReducer from "../upload_plant_photo_reducer";

export type ActivateAdminParams = __Infer<typeof ActivateAdminReducer>;
export type CreateClassSessionParams = __Infer<typeof CreateClassSessionReducer>;
export type CreateNewUserParams = __Infer<typeof CreateNewUserReducer>;
export type UploadPlantPhotoParams = __Infer<typeof UploadPlantPhotoReducer>;

