// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.identity().name("user_id"),
  mimeType: __t.string().name("mime_type"),
  photoBlob: __t.string().name("photo_blob"),
  plantAnswerType: __t.string().name("plant_answer_type"),
  reason: __t.string(),
  plantCorrectName: __t.string().name("plant_correct_name"),
  plantCorrectScientificName: __t.string().name("plant_correct_scientific_name"),
  plantCorrectType: __t.string().name("plant_correct_type"),
  plantCorrectFunFact: __t.string().name("plant_correct_fun_fact"),
  reasonFeedback: __t.string().name("reason_feedback"),
  timestamp: __t.f64(),
});
